[package]
name = "unlab-gpu"
version = "0.1.1"
authors = ["Łukasz Szpakowski <luckboy@vp.pl>"]
edition = "2018"
license = "MPL-2.0"
description = "Micro scripting language for neural networks that uses unmtx-gpu."
repository = "https://github.com/luckboy/unlab-gpu"
documentation = "https://docs.rs/unlab-gpu"
categories = ["mathematics", "science"]
keywords = ["language", "scripting-language", "matrix", "gpu", "neural-network"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
features = ["opencl", "cuda", "cuda-12060"]

[dependencies]
clap = { version = "4.6", default-features = false, features = ["std", "help", "usage", "error-context", "derive"] }
ctrlc = "3.5"
getopts = "0.2"
home = "0.5"
rand = "0.10"
rustyline = { version = "18.0", default-features = false, features = ["with-file-history"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
toml = "1.1"
unmtx-gpu = { version = "0.2.0", default-features = false }
# pkg
bzip2 = "0.6.1"
curl = "0.4"
flate2 = "1.1.9"
jammdb = "0.11"
liblzma = "0.4.1"
tar = "0.4"
zip = "8.6"
# doc
latex2mathml = "0.2.3"
markdown = "1.0"
opener = "0.8"
# plot
image = { version = "0.25", optional = true, default-features = false, features = ["png"] }
plotters = { version = "0.3", optional = true, default-features = false, features = ["bitmap_backend", "bitmap_encoder", "svg_backend", "ttf", "all_series", "all_elements"] }
softbuffer = { version = "0.4", optional = true }
winit = { version = "0.30", optional = true }

[dev-dependencies]
sealed_test = "1.1.0"

[features]
default = ["opencl", "plot"]
default_cublas = ["unmtx-gpu/default_cublas"]
default_ptx = ["unmtx-gpu/default_ptx"]
opencl = ["unmtx-gpu/opencl"]
cuda = ["unmtx-gpu/cuda"]
cuda-version-from-build-system = ["cuda", "unmtx-gpu/cuda-version-from-build-system"]
cuda-13010 = ["cuda", "unmtx-gpu/cuda-13010"]
cuda-13000 = ["cuda", "unmtx-gpu/cuda-13000"]
cuda-12090 = ["cuda", "unmtx-gpu/cuda-12090"]
cuda-12080 = ["cuda", "unmtx-gpu/cuda-12080"]
cuda-12060 = ["cuda", "unmtx-gpu/cuda-12060"]
cuda-12050 = ["cuda", "unmtx-gpu/cuda-12050"]
cuda-12040 = ["cuda", "unmtx-gpu/cuda-12040"]
cuda-12030 = ["cuda", "unmtx-gpu/cuda-12030"]
cuda-12020 = ["cuda", "unmtx-gpu/cuda-12020"]
cuda-12010 = ["cuda", "unmtx-gpu/cuda-12010"]
cuda-12000 = ["cuda", "unmtx-gpu/cuda-12000"]
cuda-11080 = ["cuda", "unmtx-gpu/cuda-11080"]
cuda-11070 = ["cuda", "unmtx-gpu/cuda-11070"]
cuda-11060 = ["cuda", "unmtx-gpu/cuda-11060"]
cuda-11050 = ["cuda", "unmtx-gpu/cuda-11050"]
cuda-11040 = ["cuda", "unmtx-gpu/cuda-11040"]
plot = ["dep:image", "dep:plotters", "dep:softbuffer", "dep:winit"]
